title: Lucas Mastro # your name (or website title) here
logo: "/images/1648640966261.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Model Validation Analyst III for Verisk Analytics <br>
  MS in Data Analytics <br>
  CEEM, IBM Certified Advanced Data Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/lucas-m-385685190/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
